/*
 * com_registry_RegistryValue.h    2011/08/07
 * Copyright (C) 2011  Yinon Michaeli
 *
 * This file is part of JRegistry.
 *
 * JRegistry is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact by e-mail if you discover any bugs or if you have a suggestion
 * to myinon2005@hotmail.com
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_registry_RegistryValue */

#ifndef _Included_com_registry_RegistryValue
#define _Included_com_registry_RegistryValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_registry_RegistryValue
 * Method:    getByteData
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_registry_RegistryValue_getByteData
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_registry_RegistryValue
 * Method:    setByteData
 * Signature: (JLjava/lang/String;I[B)I
 */
JNIEXPORT jint JNICALL Java_com_registry_RegistryValue_setByteData
  (JNIEnv *, jobject, jlong, jstring, jint, jbyteArray);

/*
 * Class:     com_registry_RegistryValue
 * Method:    getByteLength
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_RegistryValue_getByteLength
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
