/*
 * com_registry_RegistryKey.h    2012/09/15
 * Copyright (C) 2011  Yinon Michaeli
 *
 * This file is part of JRegistry.
 *
 * JRegistry is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact by e-mail if you discover any bugs or if you have a suggestion
 * to myinon2005@hotmail.com
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_registry_RegistryKey */

#ifndef _Included_com_registry_RegistryKey
#define _Included_com_registry_RegistryKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_registry_RegistryKey_serialVersionUID
#define com_registry_RegistryKey_serialVersionUID 5812494829706873509i64
#undef com_registry_RegistryKey_HKEY_CLASSES_ROOT
#define com_registry_RegistryKey_HKEY_CLASSES_ROOT -2147483648i64
#undef com_registry_RegistryKey_HKEY_CURRENT_USER
#define com_registry_RegistryKey_HKEY_CURRENT_USER -2147483647i64
#undef com_registry_RegistryKey_HKEY_LOCAL_MACHINE
#define com_registry_RegistryKey_HKEY_LOCAL_MACHINE -2147483646i64
#undef com_registry_RegistryKey_HKEY_USERS
#define com_registry_RegistryKey_HKEY_USERS -2147483645i64
#undef com_registry_RegistryKey_HKEY_PERFORMANCE_DATA
#define com_registry_RegistryKey_HKEY_PERFORMANCE_DATA -2147483644i64
#undef com_registry_RegistryKey_HKEY_CURRENT_CONFIG
#define com_registry_RegistryKey_HKEY_CURRENT_CONFIG -2147483643i64
#undef com_registry_RegistryKey_HKEY_DYN_DATA
#define com_registry_RegistryKey_HKEY_DYN_DATA -2147483642i64
#undef com_registry_RegistryKey_REG_NONE
#define com_registry_RegistryKey_REG_NONE 0L
#undef com_registry_RegistryKey_REG_SZ
#define com_registry_RegistryKey_REG_SZ 1L
#undef com_registry_RegistryKey_REG_EXPAND_SZ
#define com_registry_RegistryKey_REG_EXPAND_SZ 2L
#undef com_registry_RegistryKey_REG_BINARY
#define com_registry_RegistryKey_REG_BINARY 3L
#undef com_registry_RegistryKey_REG_DWORD
#define com_registry_RegistryKey_REG_DWORD 4L
#undef com_registry_RegistryKey_REG_DWORD_LITTLE_ENDIAN
#define com_registry_RegistryKey_REG_DWORD_LITTLE_ENDIAN 4L
#undef com_registry_RegistryKey_REG_DWORD_BIG_ENDIAN
#define com_registry_RegistryKey_REG_DWORD_BIG_ENDIAN 5L
#undef com_registry_RegistryKey_REG_LINK
#define com_registry_RegistryKey_REG_LINK 6L
#undef com_registry_RegistryKey_REG_MULTI_SZ
#define com_registry_RegistryKey_REG_MULTI_SZ 7L
#undef com_registry_RegistryKey_REG_RESOURCE_LIST
#define com_registry_RegistryKey_REG_RESOURCE_LIST 8L
#undef com_registry_RegistryKey_REG_FULL_RESOURCE_DESCRIPTOR
#define com_registry_RegistryKey_REG_FULL_RESOURCE_DESCRIPTOR 9L
#undef com_registry_RegistryKey_REG_RESOURCE_REQUIREMENTS_LIST
#define com_registry_RegistryKey_REG_RESOURCE_REQUIREMENTS_LIST 10L
#undef com_registry_RegistryKey_REG_QWORD
#define com_registry_RegistryKey_REG_QWORD 11L
#undef com_registry_RegistryKey_REG_QWORD_LITTLE_ENDIAN
#define com_registry_RegistryKey_REG_QWORD_LITTLE_ENDIAN 11L
#undef com_registry_RegistryKey_REG_FORCE_RESTORE
#define com_registry_RegistryKey_REG_FORCE_RESTORE 8L
#undef com_registry_RegistryKey_REG_WHOLE_HIVE_VOLATILE
#define com_registry_RegistryKey_REG_WHOLE_HIVE_VOLATILE 1L
#undef com_registry_RegistryKey_ERROR_CODE
#define com_registry_RegistryKey_ERROR_CODE 0L
#undef com_registry_RegistryKey_NATIVE_HANDLE
#define com_registry_RegistryKey_NATIVE_HANDLE 1L
#undef com_registry_RegistryKey_NUM_SUB_KEYS
#define com_registry_RegistryKey_NUM_SUB_KEYS 1L
#undef com_registry_RegistryKey_REG_VALUE_TYPE
#define com_registry_RegistryKey_REG_VALUE_TYPE 1L
#undef com_registry_RegistryKey_DISPOSITION
#define com_registry_RegistryKey_DISPOSITION 2L
#undef com_registry_RegistryKey_MAX_SUB_KEY_LENGTH
#define com_registry_RegistryKey_MAX_SUB_KEY_LENGTH 2L
#undef com_registry_RegistryKey_REG_VALUE_DATA
#define com_registry_RegistryKey_REG_VALUE_DATA 2L
#undef com_registry_RegistryKey_MAX_CLASS_LENGTH
#define com_registry_RegistryKey_MAX_CLASS_LENGTH 3L
#undef com_registry_RegistryKey_NUM_VALUES
#define com_registry_RegistryKey_NUM_VALUES 4L
#undef com_registry_RegistryKey_MAX_VALUE_NAME_LENGTH
#define com_registry_RegistryKey_MAX_VALUE_NAME_LENGTH 5L
#undef com_registry_RegistryKey_MAX_VALUE_LENGTH
#define com_registry_RegistryKey_MAX_VALUE_LENGTH 6L
#undef com_registry_RegistryKey_ERROR_SUCCESS
#define com_registry_RegistryKey_ERROR_SUCCESS 0L
#undef com_registry_RegistryKey_ERROR_FILE_NOT_FOUND
#define com_registry_RegistryKey_ERROR_FILE_NOT_FOUND 2L
#undef com_registry_RegistryKey_ERROR_ACCESS_DENIED
#define com_registry_RegistryKey_ERROR_ACCESS_DENIED 5L
#undef com_registry_RegistryKey_ERROR_INVALID_HANDLE
#define com_registry_RegistryKey_ERROR_INVALID_HANDLE 6L
#undef com_registry_RegistryKey_ERROR_OUTOFMEMORY
#define com_registry_RegistryKey_ERROR_OUTOFMEMORY 14L
#undef com_registry_RegistryKey_ERROR_INVALID_PARAMETER
#define com_registry_RegistryKey_ERROR_INVALID_PARAMETER 87L
#undef com_registry_RegistryKey_ERROR_PROC_NOT_FOUND
#define com_registry_RegistryKey_ERROR_PROC_NOT_FOUND 127L
#undef com_registry_RegistryKey_ERROR_ALREADY_EXISTS
#define com_registry_RegistryKey_ERROR_ALREADY_EXISTS 183L
#undef com_registry_RegistryKey_ERROR_FILENAME_EXCED_RANGE
#define com_registry_RegistryKey_ERROR_FILENAME_EXCED_RANGE 206L
#undef com_registry_RegistryKey_ERROR_BADDB
#define com_registry_RegistryKey_ERROR_BADDB 1009L
#undef com_registry_RegistryKey_ERROR_BADKEY
#define com_registry_RegistryKey_ERROR_BADKEY 1010L
#undef com_registry_RegistryKey_ERROR_CANTOPEN
#define com_registry_RegistryKey_ERROR_CANTOPEN 1011L
#undef com_registry_RegistryKey_ERROR_CANTREAD
#define com_registry_RegistryKey_ERROR_CANTREAD 1012L
#undef com_registry_RegistryKey_ERROR_CANTWRITE
#define com_registry_RegistryKey_ERROR_CANTWRITE 1013L
#undef com_registry_RegistryKey_ERROR_REGISTRY_CORRUPT
#define com_registry_RegistryKey_ERROR_REGISTRY_CORRUPT 1015L
#undef com_registry_RegistryKey_ERROR_REGISTRY_IO_FAILED
#define com_registry_RegistryKey_ERROR_REGISTRY_IO_FAILED 1016L
#undef com_registry_RegistryKey_ERROR_NOT_REGISTRY_FILE
#define com_registry_RegistryKey_ERROR_NOT_REGISTRY_FILE 1017L
#undef com_registry_RegistryKey_ERROR_KEY_DELETED
#define com_registry_RegistryKey_ERROR_KEY_DELETED 1018L
#undef com_registry_RegistryKey_ERROR_NO_LOG_SPACE
#define com_registry_RegistryKey_ERROR_NO_LOG_SPACE 1019L
#undef com_registry_RegistryKey_ERROR_KEY_HAS_CHILDREN
#define com_registry_RegistryKey_ERROR_KEY_HAS_CHILDREN 1020L
#undef com_registry_RegistryKey_ERROR_CHILD_MUST_BE_VOLATILE
#define com_registry_RegistryKey_ERROR_CHILD_MUST_BE_VOLATILE 1021L
#undef com_registry_RegistryKey_ERROR_NO_SYSTEM_RESOURCES
#define com_registry_RegistryKey_ERROR_NO_SYSTEM_RESOURCES 1450L
#undef com_registry_RegistryKey_MAX_KEY_LENGTH
#define com_registry_RegistryKey_MAX_KEY_LENGTH 255L
#undef com_registry_RegistryKey_MAX_CHARACTER_LENGTH
#define com_registry_RegistryKey_MAX_CHARACTER_LENGTH 16383L
#undef com_registry_RegistryKey_DELETE
#define com_registry_RegistryKey_DELETE 65536L
#undef com_registry_RegistryKey_WRITE_DAC
#define com_registry_RegistryKey_WRITE_DAC 262144L
#undef com_registry_RegistryKey_KEY_ALL_ACCESS
#define com_registry_RegistryKey_KEY_ALL_ACCESS 983103L
#undef com_registry_RegistryKey_KEY_CREATE_LINK
#define com_registry_RegistryKey_KEY_CREATE_LINK 32L
#undef com_registry_RegistryKey_KEY_CREATE_SUB_KEY
#define com_registry_RegistryKey_KEY_CREATE_SUB_KEY 4L
#undef com_registry_RegistryKey_KEY_ENUMERATE_SUB_KEYS
#define com_registry_RegistryKey_KEY_ENUMERATE_SUB_KEYS 8L
#undef com_registry_RegistryKey_KEY_EXECUTE
#define com_registry_RegistryKey_KEY_EXECUTE 131097L
#undef com_registry_RegistryKey_KEY_NOTIFY
#define com_registry_RegistryKey_KEY_NOTIFY 16L
#undef com_registry_RegistryKey_KEY_QUERY_VALUE
#define com_registry_RegistryKey_KEY_QUERY_VALUE 1L
#undef com_registry_RegistryKey_KEY_READ
#define com_registry_RegistryKey_KEY_READ 131097L
#undef com_registry_RegistryKey_KEY_SET_VALUE
#define com_registry_RegistryKey_KEY_SET_VALUE 2L
#undef com_registry_RegistryKey_KEY_WOW64_32KEY
#define com_registry_RegistryKey_KEY_WOW64_32KEY 512L
#undef com_registry_RegistryKey_KEY_WOW64_64KEY
#define com_registry_RegistryKey_KEY_WOW64_64KEY 256L
#undef com_registry_RegistryKey_KEY_WRITE
#define com_registry_RegistryKey_KEY_WRITE 131078L
#undef com_registry_RegistryKey_REG_OPTION_NON_VOLATILE
#define com_registry_RegistryKey_REG_OPTION_NON_VOLATILE 0L
#undef com_registry_RegistryKey_REG_OPTION_VOLATILE
#define com_registry_RegistryKey_REG_OPTION_VOLATILE 1L
#undef com_registry_RegistryKey_REG_OPTION_CREATE_LINK
#define com_registry_RegistryKey_REG_OPTION_CREATE_LINK 2L
#undef com_registry_RegistryKey_REG_OPTION_BACKUP_RESTORE
#define com_registry_RegistryKey_REG_OPTION_BACKUP_RESTORE 4L
#undef com_registry_RegistryKey_REG_OPTION_OPEN_LINK
#define com_registry_RegistryKey_REG_OPTION_OPEN_LINK 8L
#undef com_registry_RegistryKey_REG_CREATED_NEW_KEY
#define com_registry_RegistryKey_REG_CREATED_NEW_KEY 1L
#undef com_registry_RegistryKey_REG_OPENED_EXISTING_KEY
#define com_registry_RegistryKey_REG_OPENED_EXISTING_KEY 2L
#undef com_registry_RegistryKey_REG_STANDARD_FORMAT
#define com_registry_RegistryKey_REG_STANDARD_FORMAT 1L
#undef com_registry_RegistryKey_REG_LATEST_FORMAT
#define com_registry_RegistryKey_REG_LATEST_FORMAT 2L
#undef com_registry_RegistryKey_REG_NO_COMPRESSION
#define com_registry_RegistryKey_REG_NO_COMPRESSION 4L
#undef com_registry_RegistryKey_REG_NOTIFY_CHANGE_NAME
#define com_registry_RegistryKey_REG_NOTIFY_CHANGE_NAME 1L
#undef com_registry_RegistryKey_REG_NOTIFY_CHANGE_ATTRIBUTES
#define com_registry_RegistryKey_REG_NOTIFY_CHANGE_ATTRIBUTES 2L
#undef com_registry_RegistryKey_REG_NOTIFY_CHANGE_LAST_SET
#define com_registry_RegistryKey_REG_NOTIFY_CHANGE_LAST_SET 4L
#undef com_registry_RegistryKey_REG_NOTIFY_CHANGE_SECURITY
#define com_registry_RegistryKey_REG_NOTIFY_CHANGE_SECURITY 8L
#undef com_registry_RegistryKey_SE_BACKUP_NAME
#define com_registry_RegistryKey_SE_BACKUP_NAME 4206592L
#undef com_registry_RegistryKey_SE_RESTORE_NAME
#define com_registry_RegistryKey_SE_RESTORE_NAME 4206614L
#undef com_registry_RegistryKey_DEFAULT_FILTER
#define com_registry_RegistryKey_DEFAULT_FILTER 5L
#undef com_registry_RegistryKey_ALL_FILTERS
#define com_registry_RegistryKey_ALL_FILTERS 15L
#undef com_registry_RegistryKey_NULL_NATIVE_HANDLE
#define com_registry_RegistryKey_NULL_NATIVE_HANDLE 0L
#undef com_registry_RegistryKey_HKEY_CLASSES_ROOT_INDEX
#define com_registry_RegistryKey_HKEY_CLASSES_ROOT_INDEX 0L
#undef com_registry_RegistryKey_HKEY_CURRENT_USER_INDEX
#define com_registry_RegistryKey_HKEY_CURRENT_USER_INDEX 1L
#undef com_registry_RegistryKey_HKEY_LOCAL_MACHINE_INDEX
#define com_registry_RegistryKey_HKEY_LOCAL_MACHINE_INDEX 2L
#undef com_registry_RegistryKey_HKEY_USERS_INDEX
#define com_registry_RegistryKey_HKEY_USERS_INDEX 3L
#undef com_registry_RegistryKey_HKEY_PERFORMANCE_DATA_INDEX
#define com_registry_RegistryKey_HKEY_PERFORMANCE_DATA_INDEX 4L
#undef com_registry_RegistryKey_HKEY_CURRENT_CONFIG_INDEX
#define com_registry_RegistryKey_HKEY_CURRENT_CONFIG_INDEX 5L
#undef com_registry_RegistryKey_HKEY_DYN_DATA_INDEX
#define com_registry_RegistryKey_HKEY_DYN_DATA_INDEX 6L
#undef com_registry_RegistryKey_LIBRARY_VERSION
#define com_registry_RegistryKey_LIBRARY_VERSION 17301505L
/*
 * Class:     com_registry_RegistryKey
 * Method:    initIDs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_registry_RegistryKey_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_registry_RegistryKey
 * Method:    getComputerName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_RegistryKey_getComputerName
  (JNIEnv *, jclass);

/*
 * Class:     com_registry_RegistryKey
 * Method:    formatErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_RegistryKey_formatErrorMessage
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_registry_RegistryKey
 * Method:    RegGetSetKeySecurity
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_registry_RegistryKey_RegGetSetKeySecurity
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_registry_RegistryKey
 * Method:    getClassName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_RegistryKey_getClassName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_registry_RegistryKey
 * Method:    getCurrentUserSid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_RegistryKey_getCurrentUserSid
  (JNIEnv *, jclass);

/*
 * Class:     com_registry_RegistryKey
 * Method:    getSystemTime
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_registry_RegistryKey_getSystemTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_registry_RegistryKey
 * Method:    lastModified
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_registry_RegistryKey_lastModified
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_registry_RegistryKey
 * Method:    searchInteger
 * Signature: (JIJ[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_RegistryKey_searchInteger
  (JNIEnv *, jobject, jlong, jint, jlong, jobjectArray);

/*
 * Class:     com_registry_RegistryKey
 * Method:    searchString
 * Signature: (JIZZZLjava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_RegistryKey_searchString
  (JNIEnv *, jobject, jlong, jint, jboolean, jboolean, jboolean, jstring, jobjectArray);

/*
 * Class:     com_registry_RegistryKey
 * Method:    searchBinary
 * Signature: (JI[B[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_RegistryKey_searchBinary
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
