/*
 * com_registry_WinRegistryAPI.h    2011/08/09
 * Copyright (C) 2011  Yinon Michaeli
 *
 * This file is part of JRegistry.
 *
 * JRegistry is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact by e-mail if you discover any bugs or if you have a suggestion
 * to myinon2005@hotmail.com
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_registry_WinRegistryAPI */

#ifndef _Included_com_registry_WinRegistryAPI
#define _Included_com_registry_WinRegistryAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    ExpandEnvironmentStrings
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_WinRegistryAPI_ExpandEnvironmentStrings
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    GetSystemRegistryQuota
 * Signature: ()Lcom/registry/RegistryQuota;
 */
JNIEXPORT jobject JNICALL Java_com_registry_WinRegistryAPI_GetSystemRegistryQuota
  (JNIEnv *, jclass);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegCloseKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegCloseKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegConnectRegistry
 * Signature: (Ljava/lang/String;J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_registry_WinRegistryAPI_RegConnectRegistry
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegCopyTree
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegCopyTree
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegCreateKeyEx
 * Signature: (JLjava/lang/String;IILjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_registry_WinRegistryAPI_RegCreateKeyEx
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegDeleteKey
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegDeleteKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegDeleteKeyEx
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegDeleteKeyEx
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegDeleteKeyValue
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegDeleteKeyValue
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegDeleteLink
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegDeleteLink
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegDeleteTree
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegDeleteTree
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegDeleteValue
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegDeleteValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegDisableReflectionKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegDisableReflectionKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegEnableReflectionKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegEnableReflectionKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegEnumKeyEx
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_WinRegistryAPI_RegEnumKeyEx
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegEnumValue
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_WinRegistryAPI_RegEnumValue
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegFlushKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegFlushKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegGetLinkLocation
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_registry_WinRegistryAPI_RegGetLinkLocation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegIsLinkKey
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_registry_WinRegistryAPI_RegIsLinkKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegLoadKey
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegLoadKey
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegNotifyChangeKeyValue
 * Signature: (JZIJZ)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegNotifyChangeKeyValue
  (JNIEnv *, jclass, jlong, jboolean, jint, jlong, jboolean);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegOpenKeyEx
 * Signature: (JLjava/lang/String;I)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_registry_WinRegistryAPI_RegOpenKeyEx
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegQueryInfoKey
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_registry_WinRegistryAPI_RegQueryInfoKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegQueryMultipleValues
 * Signature: (J[Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_registry_WinRegistryAPI_RegQueryMultipleValues
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegQueryReflectionKey
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_registry_WinRegistryAPI_RegQueryReflectionKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegQueryValueEx
 * Signature: (JLjava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_registry_WinRegistryAPI_RegQueryValueEx
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegRenameKey
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegRenameKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegReplaceKey
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegReplaceKey
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegRestoreKey
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegRestoreKey
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegSaveKey
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegSaveKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegSaveKeyEx
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegSaveKeyEx
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegSetLinkValue
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegSetLinkValue
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegSetValueEx
 * Signature: (JLjava/lang/String;ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegSetValueEx
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    RegUnLoadKey
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WinRegistryAPI_RegUnLoadKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_registry_WinRegistryAPI
 * Method:    SetPrivilege
 * Signature: (ZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_registry_WinRegistryAPI_SetPrivilege
  (JNIEnv *, jclass, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
