/*
 * com_registry_WatchData.h    2012/09/15
 * Copyright (C) 2011  Yinon Michaeli
 *
 * This file is part of JRegistry.
 *
 * JRegistry is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact by e-mail if you discover any bugs or if you have a suggestion
 * to myinon2005@hotmail.com
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_registry_WatchData */

#ifndef _Included_com_registry_WatchData
#define _Included_com_registry_WatchData
#ifdef __cplusplus
extern "C" {
#endif
#undef com_registry_WatchData_WAIT_OBJECT_0
#define com_registry_WatchData_WAIT_OBJECT_0 0L
#undef com_registry_WatchData_WAIT_ABANDONED
#define com_registry_WatchData_WAIT_ABANDONED 80L
#undef com_registry_WatchData_WAIT_TIMEOUT
#define com_registry_WatchData_WAIT_TIMEOUT 102L
#undef com_registry_WatchData_WAIT_FAILED
#define com_registry_WatchData_WAIT_FAILED -1L
#undef com_registry_WatchData_INFINITE
#define com_registry_WatchData_INFINITE -1L
/*
 * Class:     com_registry_WatchData
 * Method:    CreateEvent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_registry_WatchData_CreateEvent
  (JNIEnv *, jclass);

/*
 * Class:     com_registry_WatchData
 * Method:    WaitForSingleObject
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_registry_WatchData_WaitForSingleObject
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_registry_WatchData
 * Method:    CloseHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_registry_WatchData_CloseHandle
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
